apiVersion: v1
kind: Secret
metadata:
  name: ${name}
  namespace: kafka
type: Opaque
stringData:
  username: ${DB_USER}
  host: ${DB_HOST}
  port: "${DB_PORT}"
  db: ${DB_NAME}
data:
  password: ${DB_PWD}
