apiVersion: apps/v1
kind: Deployment
metadata:
  name: insert-data-rds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insert-data-rds
  template:
    metadata:
      labels:
        app: insert-data-rds
    spec:
      containers:
      - name: insert-data-rds
        image: hieupham0607/debezium-publisher:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting insert-data-rds job..."
          # Run your main script or command
          python app.py
          # Keep the container running after completion
          while true; do sleep 10; done

# psql -h debezium-demo.cootgowfrctk.us-east-1.rds.amazonaws.com -U postgres -d postgres