apiVersion: apps/v1
kind: Deployment
metadata:
  name: insert-data-db
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insert-data-db
  template:
    metadata:
      labels:
        app: insert-data-db
    spec:
      containers:
      - name: insert-data-db
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
        image: hieupham0607/debezium-publisher:latest
        imagePullPolicy: Always
        env:
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: host
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB
          value: "mysql"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: host
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: host
        - name: MONGO_DB
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: host
        - name: MONGO_COLLECTION
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: host