apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: opensearch-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.aiven.kafka.connect.opensearch.OpensearchSinkConnector
  tasksMax: 1
  config:
    topics: mysql.public.test_table,postgres.public.test_table,
    connection.url: $${secrets:kafka/opensearch-secret:host} # https://opensearch-cluster-master.opensearch.svc.cluster.local:9200
    connection.username: $${secrets:kafka/opensearch-secret:user}
    connection.password: $${secrets:kafka/opensearch-secret:password}
    key.ignore: "false"
    schema.ignore: "false"
    connect.timeout.ms: 10000
    read.timeout.ms: 10000
    value.converter: org.apache.kafka.connect.json.JsonConverter
    type.name: crm_cdc.public.customer_records
    key.converter: org.apache.kafka.connect.storage.StringConverter
    errors.retry.timeout: "60000"
    errors.retry.delay.max.ms: "5000"
    errors.log.enable: "true"
    errors.log.include.messages: "true"
    errors.deadletterqueue.topic.name: "opensearch-records-dlq"
    errors.deadletterqueue.context.headers.enable: "true"