apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
  namespace: kafka
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-secret", "mongo-secret", "opensearch-secret", "mysql-secret"]
    verbs: ["get"]

    # psql -h debezium-demo-postgres.cjo4ko044lu6.us-east-1.rds.amazonaws.com -U postgres